# **Teoria dos Grafos e Computabilidade**
##**Trabalho Prático 1**

###**Professor:**  *Felipe Augusto Lara Soares*
**Grupo:** 
*   *Gustavo de Castro Nogueira*
*   *Horácio Salvador Ngunga*
*   *Nelson de Campos Nolasco*
*   *Rafaella Cristina de Sousa Sacramento*
*   *Vitor de Souza Xavier*
*   *Vitor José Lara Bastos*
---

## **Etapa 1 - (3 pontos)**


O trabalho consiste em ler o arquivo disponibilizado no Canvas que contém dados referentes às latitudes e longitudes de algumas cidades brasileiras (você pode escolher ler: CSV ou JSON).

Após a leitura desses dados, o programa deve ser capaz de gerar um grafo não direcionado e ponderado que represente esse contexto, considerando os vértices como as cidades brasileiras (presentes no arquivo) e as arestas como as rotas entre essas cidades, cujo peso é a distância da rota.

**Informação Importante:** para cada cidade criada (vértice), considere que ela possua ligações (arestas) somente com as três cidades mais próximas a ela. Essa característica irá deixar o nosso grafo um pouco fora do contexto real, porém será importante para testarmos diferentes alternativas nos algoritmos que serão criados nas próximas etapas.

Como o arquivo contém latitudes e longitudes, fica como responsabilidade do grupo procurar como encontrar distância entre diferentes latitudes e longitudes, bem como desenvolver o programa responsável por encontrar essa distância e definir quais arestas serão criadas.

*   Entregáveis etapa 1: código para leitura do arquivo e criação do grafo.


---



# **PRIMEIRA PARTE:**



### > ***Baixar o arquivo 'br.csv', analisá-lo, e prepará-lo para gerar o grafo solicitado nesta Etapa 1 do trabalho.***





> Primeiramente, serão necessários instalar e importar as bibliotecas a serem utilizadas no tratamento dos dados do arquivo *'Br.csv'* disponibilizado.




#### ! -> se estiver utilizando o google colab
#### % -> se estiver utilizando o vscode

In [2]:
# !pip install haversine 
# %pip install haversine 

In [3]:
import pandas as pd #biblioteca Python que fornece ferramentas para análise e manipulação de dados - criar, ler, visualizar, printar infos de DataFrame (df)
import haversine



> Importar o arquivo br.csv disponibilizado com os dados de latitude e longitude a ser trabalhado.
Neste caso, o arquivo "br.csv" deverá ser localizado no diretório onde se encontra no computador local.



In [4]:
#### se estiver no colab, rodar a célula abaixo e anexar o arquivo br.csv 

In [5]:
# from google.colab import files
# data_to_load = files.upload()



> Ler e visualizar o DataFrame baixado 'br.csv'

In [6]:
df = pd.read_csv('br.csv') #Função usada para ler e transformar os dados do arquivo 'csv' em um DataFrame (aqui abreviada para 'df')

> Explorando as informações do DataFrame "br.csv" disponibilizado para ser usado no trabalho

In [7]:
df.head(110) #Função usada para retornar as primeiras n (5 por padrão) linhas do DataFrame. Aqui foi utilizada 10 entre parênteses para visualizar as 10 primeiras linhas.

city      lat      lng country iso2         admin_name  \
0         São Paulo -23.5504 -46.6339  Brazil   BR          São Paulo   
1    Rio de Janeiro -22.9083 -43.1964  Brazil   BR     Rio de Janeiro   
2    Belo Horizonte -19.9281 -43.9419  Brazil   BR       Minas Gerais   
3          Brasília -15.7939 -47.8828  Brazil   BR   Distrito Federal   
4          Salvador -12.9708 -38.5108  Brazil   BR              Bahia   
..              ...      ...      ...     ...  ...                ...   
105      Imperatriz  -5.5258 -47.4758  Brazil   BR           Maranhão   
106   Foz do Iguaçu -25.5400 -54.5875  Brazil   BR             Paraná   
107        Cascavel -24.9558 -53.4553  Brazil   BR             Paraná   
108          Viamão -30.0808 -51.0228  Brazil   BR  Rio Grande do Sul   
109        Gravataí -29.9433 -50.9939  Brazil   BR  Rio Grande do Sul   

     capital  population  population_proper  
0      admin    22046000           12252023  
1      admin    12272000            6520000  
2      admin     5159000            2502557  
3    primary     3015268            3015268  
4      admin     2886698            2886698  
..       ...         ...                ...  
105      NaN      259337             259337  
106      NaN      258248             258248  
107      NaN      257172             201428  
108      NaN      256302             256302  
109      NaN      255660             255660  

[110 rows x 9 columns]

In [8]:
len(df) #Função que retorna a contagem do número de linhas do DataFrame, que no caso coincide com o número de cidades a terem os dados de latitude e longitude a serem manipuladas no trabalho.

110

In [9]:
df.info() #dataframe.info() é usada para obter um resumo conciso do dataframe. É muito útil ao fazer análises exploratórias dos dados. Para obter uma visão geral rápida do conjunto de dados.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   city               110 non-null    object 
 1   lat                110 non-null    float64
 2   lng                110 non-null    float64
 3   country            110 non-null    object 
 4   iso2               110 non-null    object 
 5   admin_name         110 non-null    object 
 6   capital            27 non-null     object 
 7   population         110 non-null    int64  
 8   population_proper  110 non-null    int64  
dtypes: float64(2), int64(2), object(5)
memory usage: 7.9+ KB


> Próximo passo, limpeza do DataFrame, removendo colunas e dados não necessários para o trabalho, retornando apenas as colunas City, lat, lng (que informam o nome da cidade, sua latitude e longitude).

>Por padrão, as operações efetuadas no DataFrame não o afetam. Assim, ao remover uma coluna, linha etc., o que o Pandas faz é devolver um novo DataFrame sem aquele dado. Ou seja, o DataFrame original se mantém intacto.

> O que se pode fazer para resolver isso é atribuir esse DataFrame que é devolvido pelo método na mesma variável:

In [10]:
df = df.drop(columns=["country", "iso2", "admin_name", "capital", "population", "population_proper"])
df.head()

city      lat      lng
0       São Paulo -23.5504 -46.6339
1  Rio de Janeiro -22.9083 -43.1964
2  Belo Horizonte -19.9281 -43.9419
3        Brasília -15.7939 -47.8828
4        Salvador -12.9708 -38.5108

> Agora, passa-se ao cálculo das distâncias das cidades a partir dos dados de latitude e longitude.

> Aqui foi usada a biblioteca **Haversine** do Python para calcular a distância (em várias unidades) entre dois pontos na terra usando sua latitude e longitude. A unidade padrão é o Km.

> No final se terá um array 'finalMat' com as cidades e respectivas distâncias em Km.

In [11]:
from haversine import haversine, haversine_vector, Unit

In [12]:
# Pegando os valores da tabela
lats = pd.Series(df.lat.values.flatten())
lngs = pd.Series(df.lng.values.flatten())
cities = pd.Series(df.city.values.flatten())

#sp = (lats[0], lngs[0])
#rj = (lats[1], lngs[1])
#bh = (lats[2], lngs[2])
#br = (lats[3], lngs[3])
#sv = (lats[4], lngs[4])

# Criando o vetor que terá a coordenada de cada cidade
combVet = []
for x in range(len(lats)):
  aux = (lats[x], lngs[x])
  combVet.append(aux)

# Calculando a distância das cidades (*ATENÇÃO* em cada vetor há o valor 0)
allVet = haversine_vector(combVet, combVet, comb=True) 


# Criando uma matriz que terá TODAS as distâncias e suas respectivas cidades
arrayAux = []
finalMat = []
for i in range(len(lats)):
  arrayAux = [] # Limpando o array
  for j in range(len(lats)):
    aux = (allVet[i][j], cities[j]) # Pegando a matriz das distâncias e adicionando o nome da cidade que foi calculado a distância
    arrayAux.append(aux) # Inserindo em um array auxiliar (ex: [(...) ...., (13.2313, 'São Paulo'), .... (...)])
    
  arrayAux.sort() # Ordenando-o para inserir corretamente no finalVet
  finalMat.append(arrayAux)

print(finalMat[23]) 



[(0.0, 'São Bernardo do Campo'), (5.203339801571569, 'Santo André'), (5.954008749780465, 'Diadema'), (11.000637576879159, 'Mauá'), (17.43219351404239, 'São Paulo'), (21.692535235839074, 'Taboão da Serra'), (25.46923702954073, 'Guarulhos'), (29.245828790417757, 'Osasco'), (30.870751114045483, 'Suzano'), (31.91615049639615, 'Itaquaquecetuba'), (33.51498103518244, 'Carapicuíba'), (34.73177449608012, 'São Vicente'), (37.68189022430787, 'Barueri'), (37.85968736220912, 'Santos'), (38.40483645500058, 'Praia Grande'), (42.400428431802474, 'Mogi das Cruzes'), (45.778253776098765, 'Guarujá'), (65.15323537406795, 'Jundiaí'), (89.80687922373005, 'São José dos Campos'), (93.44468027189578, 'Sorocaba'), (101.50426196565223, 'Campinas'), (120.59499209652519, 'Sumaré'), (127.00512443667235, 'Taubaté'), (131.92092022638917, 'Americana'), (151.9394229779001, 'Limeira'), (154.52120689691685, 'Piracicaba'), (283.3434076657737, 'Volta Redonda'), (297.922289705036, 'Bauru'), (307.4529947507336, 'Ribeirão Pr

In [13]:
df.head() #Como informado a cima, se lermos o DataFrame original ele continua intacto


city      lat      lng
0       São Paulo -23.5504 -46.6339
1  Rio de Janeiro -22.9083 -43.1964
2  Belo Horizonte -19.9281 -43.9419
3        Brasília -15.7939 -47.8828
4        Salvador -12.9708 -38.5108

In [14]:
#transformando o Array 'finalMat' novamente em um DataFrame
ciddist_df = pd.DataFrame(finalMat)

In [15]:
ciddist_df.head() #Visualizando as 5 primeiras linhas do DataFrame contendo a cidade referência e distâncias em km das demais

0                                      1    \
0       (0.0, São Paulo)  (13.402523160668702, Taboão da Serra)   
1  (0.0, Rio de Janeiro)           (9.904048657545651, Niterói)   
2  (0.0, Belo Horizonte)         (11.715607237739366, Contagem)   
3        (0.0, Brasília)         (128.78251122229827, Anápolis)   
4        (0.0, Salvador)         (36.497896929423185, Camaçari)   

                                        2                                 3    \
0           (13.850728557490909, Guarulhos)      (15.09822561330356, Diadema)   
1         (17.178006560588464, São Gonçalo)      (33.712115697912445, Iguaçu)   
2  (23.479498947044757, Ribeirão das Neves)       (27.109446198270142, Betim)   
3             (176.70737169015752, Goiânia)  (349.99210461118764, Uberlândia)   
4       (92.604279019326, Feira de Santana)     (277.41932137267884, Aracaju)   

                                         4    \
0          (15.687580109354368, Santo André)   
1            (44.88088899075216, Petrópolis)   
2             (155.73696186323843, Ipatinga)   
3                 (439.68495230787, Uberaba)   
4  (327.9823255801843, Vitória da Conquista)   

                                   5    \
0          (16.22503354614594, Osasco)   
1  (102.49176161726693, Volta Redonda)   
2         (179.92635204512297, Abaeté)   
3   (441.5239562274328, Montes Claros)   
4       (453.5711458983849, Petrolina)   

                                          6    \
0  (17.43219351404239, São Bernardo do Campo)   
1           (128.1992048813632, Juiz de Fora)   
2           (213.2191224599671, Juiz de Fora)   
3                 (454.2986748210508, Abaeté)   
4                (476.05199334612536, Maceió)   

                                         7    \
0          (20.810081442619314, Carapicuíba)   
1                (230.9929410502458, Campos)   
2  (240.9282091982431, Governador Valadares)   
3                 (530.070657515641, Franca)   
4               (590.2894839260042, Caruaru)   

                                          8    \
0                   (21.94245877149327, Mauá)   
1                (241.3541543505496, Taubaté)   
2          (289.0410817223904, Volta Redonda)   
3  (580.7473869361884, São José do Rio Prêto)   
4                  (645.4153634042875, Crato)   

                                         9    ...  \
0               (25.10581760201661, Barueri)  ...   
1  (276.93395482694086, São José dos Campos)  ...   
2            (297.2511500470614, Petrópolis)  ...   
3    (597.1771487304582, Ribeirão das Neves)  ...   
4     (646.2803652750597, Juazeiro do Norte)  ...   

                                100                                 101  \
0    (2369.969740500857, Fortaleza)           (2465.06417634481, Belém)   
1       (2453.2678618483174, Belém)    (2459.7385777748214, Ananindeua)   
2       (2113.0804995460753, Belém)    (2119.5130637437005, Ananindeua)   
3  (1760.7755852761259, Parnamirim)         (1773.9441914462814, Natal)   
4      (2296.8443505560986, Viamão)  (2304.5964284629063, Porto Alegre)   

                                 102                               103  \
0    (2465.86865283367, Porto Velho)  (2473.9221864383303, Ananindeua)   
1        (2543.9971296190242, Natal)       (2689.193087365609, Macapá)   
2        (2274.3912129920755, Natal)       (2351.261188900504, Macapá)   
3         (1794.21349531997, Macapá)      (1833.135676404752, Pelotas)   
4  (2436.3693656858463, Santa Maria)       (2472.5948604437735, Natal)   

                                 104                                105  \
0        (2502.6152790171823, Crato)        (2665.660718747892, Macapá)   
1  (2710.4104429456274, Porto Velho)         (2728.925285261962, Crato)   
2  (2479.0485587222865, Porto Velho)         (2481.072266168841, Crato)   
3        (1891.3102959256305, Crato)  (1906.8988447953802, Porto Velho)   
4       (2522.800299370199, Pelotas)        (2606.810370020706, Manaus)   

                            106             

> Em sequência serão deletadas as colunas com as cidades à cima da terceira menor distância em relação à cidade referenciada na primeira coluna, conforme solicitado na **Etapa 1** do trabalho para a geração do grafo.

> Usou-se o comando *Drop* do Pandas para remover as colunas 4 à 109.

In [16]:
cid_menores_dist_df = ciddist_df.drop(columns=[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109])
cid_menores_dist_df.head()

0                                      1  \
0       (0.0, São Paulo)  (13.402523160668702, Taboão da Serra)   
1  (0.0, Rio de Janeiro)           (9.904048657545651, Niterói)   
2  (0.0, Belo Horizonte)         (11.715607237739366, Contagem)   
3        (0.0, Brasília)         (128.78251122229827, Anápolis)   
4        (0.0, Salvador)         (36.497896929423185, Camaçari)   

                                          2                                 3  
0           (13.850728557490909, Guarulhos)      (15.09822561330356, Diadema)  
1         (17.178006560588464, São Gonçalo)      (33.712115697912445, Iguaçu)  
2  (23.479498947044757, Ribeirão das Neves)       (27.109446198270142, Betim)  
3             (176.70737169015752, Goiânia)  (349.99210461118764, Uberlândia)  
4       (92.604279019326, Feira de Santana)     (277.41932137267884, Aracaju)

In [17]:
cid_menores_dist_df.head () #Visualizando as 5 primeiras linhas do DataFrame contendo a cidade referência e distâncias em km das três outras mais próximas.

0                                      1  \
0       (0.0, São Paulo)  (13.402523160668702, Taboão da Serra)   
1  (0.0, Rio de Janeiro)           (9.904048657545651, Niterói)   
2  (0.0, Belo Horizonte)         (11.715607237739366, Contagem)   
3        (0.0, Brasília)         (128.78251122229827, Anápolis)   
4        (0.0, Salvador)         (36.497896929423185, Camaçari)   

                                          2                                 3  
0           (13.850728557490909, Guarulhos)      (15.09822561330356, Diadema)  
1         (17.178006560588464, São Gonçalo)      (33.712115697912445, Iguaçu)  
2  (23.479498947044757, Ribeirão das Neves)       (27.109446198270142, Betim)  
3             (176.70737169015752, Goiânia)  (349.99210461118764, Uberlândia)  
4       (92.604279019326, Feira de Santana)     (277.41932137267884, Aracaju)

In [18]:
#será realizada a alteração do label (de 0,1,2,3 para: origem, distância_1, distancia_2,distancia_3) para maior clareza
cid_menores_dist_df.rename({0: "origem"}, axis=1, inplace=True)
cid_menores_dist_df.rename({1: "distancia_1"}, axis=1, inplace=True)
cid_menores_dist_df.rename({2: "distancia_2"}, axis=1, inplace=True)
cid_menores_dist_df.rename({3: "distancia_3"}, axis=1, inplace=True)
cid_menores_dist_df


origem                            distancia_1  \
0         (0.0, São Paulo)  (13.402523160668702, Taboão da Serra)   
1    (0.0, Rio de Janeiro)           (9.904048657545651, Niterói)   
2    (0.0, Belo Horizonte)         (11.715607237739366, Contagem)   
3          (0.0, Brasília)         (128.78251122229827, Anápolis)   
4          (0.0, Salvador)         (36.497896929423185, Camaçari)   
..                     ...                                    ...   
105      (0.0, Imperatriz)           (182.59304432726947, Marabá)   
106   (0.0, Foz do Iguaçu)         (131.09376165940165, Cascavel)   
107        (0.0, Cascavel)    (131.09376165940165, Foz do Iguaçu)   
108          (0.0, Viamão)         (15.540484048609208, Gravataí)   
109        (0.0, Gravataí)           (15.540484048609208, Viamão)   

                                  distancia_2  \
0             (13.850728557490909, Guarulhos)   
1           (17.178006560588464, São Gonçalo)   
2    (23.479498947044757, Ribeirão das Neves)   
3               (176.70737169015752, Goiânia)   
4         (92.604279019326, Feira de Santana)   
..                                        ...   
105                (466.7217032215074, Belém)   
106             (356.55823044447834, Maringá)   
107             (229.40999124578008, Maringá)   
108         (20.64338626667539, Porto Alegre)   
109              (18.119526230195792, Canoas)   

                            distancia_3  
0          (15.09822561330356, Diadema)  
1          (33.712115697912445, Iguaçu)  
2           (27.109446198270142, Betim)  
3      (349.99210461118764, Uberlândia)  
4         (277.41932137267884, Aracaju)  
..                                  ...  
105      (473.139168845076, Ananindeua)  
106      (426.23546617447226, Londrina)  
107      (295.97750374023036, Londrina)  
108        (23.427709201810405, Canoas)  
109  (24.821096491418178, Porto Alegre)  

[110 rows x 4 columns]



---



# **SEGUNDA PARTE:**



### > ***Geração do grafo solicitado nesta Etapa 1 do trabalho.***

> A partir do Dataframe 'cid_menores_dist' (as três cidades com menores distâncias entre si, de cada uma das 110), será gerado o grafo cujos **Vértices** serão os nomes das cidades e as **Arestas** a distância em Km entre cada uma das três mais próximas.

## Criando as classes necessárias:

In [19]:
class Aresta():
    def __init__(self, vertice1, vertice2, peso):
        self.vertices = tuple((vertice1, vertice2))
        self.peso = peso


In [20]:
class Vertice():
    def __init__(self, rotulo):
        self.arestasIncidentes = []
        self.rotulo = rotulo #Nome da cidade

    def addAresta(self, aresta):
        self.arestasIncidentes.append(aresta)

    def getRotulo(self):
        return self.rotulo


In [21]:
class Grafo():
    def __init__(self):
        self.vertices = []
    
    def dataframeToGrafo(self, dataframe):
        # Cria os vertices apartir do dataframe coluna 'origem':
        for i in range(len(dataframe)): # iterar linhas do dataframe
            tuplaOrigem = tuple(dataframe['origem'][i])
            verticeOrigem = Vertice(str(tuplaOrigem[1]))
            self.addVertice(verticeOrigem)

        # Cria arestas associando os vertices criados acima, apartir das colunas distancia_1, distancia_2, distancia_3:
        for linha in range(len(dataframe)):  # iterar linhas do dataframe
            for i in range(1,4): #iterar colunas
                nomeColuna = f'distancia_{i}'
                tuplaCidadeDistancia = tuple(dataframe[nomeColuna][linha])
                distancia = tuplaCidadeDistancia[0]
                nomeCidadeDestino = tuplaCidadeDistancia[1]
                nomeCidadeOrigem = dataframe['origem'][linha][1]

                indexCidadeOrigem = self.getIndexCidadeByName(nomeCidade=nomeCidadeOrigem)
                indexCidadeDestino = self.getIndexCidadeByName(nomeCidade=nomeCidadeDestino)

                aresta = Aresta(vertice1=self.vertices[indexCidadeOrigem], vertice2=self.vertices[indexCidadeDestino], peso=distancia)
                self.vertices[indexCidadeOrigem].addAresta(aresta)
                self.vertices[indexCidadeDestino].addAresta(aresta)



        
    def getIndexCidadeByName(self, nomeCidade: str):
        for v in range(len(self.vertices)):
            if self.vertices[v].getRotulo() == nomeCidade:
                return v
        return None



    def addVertice(self, vertice):
        self.vertices.append(vertice)

  
    def _gerarDFMatrizZerada(self):
        cidades = [vertice.getRotulo() for vertice in self.vertices]
        matriz = {}
        
        for cidade in cidades:
            linhaDF = []
            for i in range(len(cidades)):
                linhaDF.append(0)
            matriz[cidade] = linhaDF

        dfMatriz = pd.DataFrame(data=matriz, columns=cidades, index=cidades )
        return dfMatriz

    def gerarMatrizAdjacencia(self):
        if len(self.vertices) == 0:
            return None

        dfMatriz = self._gerarDFMatrizZerada()
        
        for vertice in self.vertices:
            for aresta in vertice.arestasIncidentes:
                dfMatriz.loc[aresta.vertices[0].getRotulo(), aresta.vertices[1].getRotulo()] = aresta.peso
                dfMatriz.loc[aresta.vertices[1].getRotulo(), aresta.vertices[0].getRotulo()] = aresta.peso

        return dfMatriz

In [22]:
grafoCidades = Grafo()
grafoCidades.dataframeToGrafo(cid_menores_dist_df)
matriz = grafoCidades.gerarMatrizAdjacencia()
matriz

São Paulo  Rio de Janeiro  Belo Horizonte  Brasília  Salvador  \
São Paulo             0.0             0.0             0.0       0.0       0.0   
Rio de Janeiro        0.0             0.0             0.0       0.0       0.0   
Belo Horizonte        0.0             0.0             0.0       0.0       0.0   
Brasília              0.0             0.0             0.0       0.0       0.0   
Salvador              0.0             0.0             0.0       0.0       0.0   
...                   ...             ...             ...       ...       ...   
Imperatriz            0.0             0.0             0.0       0.0       0.0   
Foz do Iguaçu         0.0             0.0             0.0       0.0       0.0   
Cascavel              0.0             0.0             0.0       0.0       0.0   
Viamão                0.0             0.0             0.0       0.0       0.0   
Gravataí              0.0             0.0             0.0       0.0       0.0   

                Fortaleza  Curitiba  Manaus  Recife       Belém  ...  \
São Paulo             0.0       0.0     0.0     0.0    0.000000  ...   
Rio de Janeiro        0.0       0.0     0.0     0.0    0.000000  ...   
Belo Horizonte        0.0       0.0     0.0     0.0    0.000000  ...   
Brasília              0.0       0.0     0.0     0.0    0.000000  ...   
Salvador              0.0       0.0     0.0     0.0    0.000000  ...   
...                   ...       ...     ...     ...         ...  ...   
Imperatriz            0.0       0.0     0.0     0.0  466.721703  ...   
Foz do Iguaçu         0.0       0.0     0.0     0.0    0.000000  ...   
Cascavel              0.0       0.0     0.0     0.0    0.000000  ...   
Viamão                0.0       0.0     0.0     0.0    0.000000  ...   
Gravataí              0.0       0.0     0.0     0.0    0.000000  ...   

                Parnamirim  Sumaré    Ipatinga  Volta Redonda  Barueri  \
São Paulo              0.0     0.0    0.000000       0.000000      0.0   
Rio de Janeiro         0.0     0.0    0.000000     102.491762      0.0   
Belo Horizonte         0.0     0.0  155.736962       0.000000      0.0   
Brasília               0.0     0.0    0.000000       0.000000      0.0   
Salvador               0.0     0.0    0.000000       0.000000      0.0   
...                    ...     ...         ...            ...      ...   
Imperatriz             0.0     0.0    0.000000       0.000000      0.0   
Foz do Iguaçu          0.0     0.0    0.000000       0.000000      0.0   
Cascavel               0.0     0.0    0.000000       0.000000      0.0   
Viamão                 0.0     0.0    0.000000       0.000000      0.0   
Gravataí               0.0     0.0    0.000000       0.000000      0.0   

                Imperatriz  Foz do Iguaçu    Cascavel     Viamão   Gravataí  
São Paulo              0.0       0.000000    0.000000   0.000000   0.000000  
Rio de Janeiro         0.0       0.000000    0.000000   0.000000   0.000000  
Belo Horizonte         0.0       0.000000    0.000000   0.000000   0.000000  
Brasília               0.0       0.000000    0.000000   0.000000   0.000000  
Salvador               0.0       0.000000    0.000000   0.000000   0.000000  
...                    ...            ...         ...        ...        ...  
Imperatriz             0.0       0.000000    0.000000   0.000000   0.000000  
Foz do Iguaçu          0.0       0.000000  131.093762   0.000000   0.000000  
Cascavel               0.0     131.093762    0.000000   0.000000   0.000000  
Viamão                 0.0       0.000000    0.000000   0.000000  15.540484  
Gravataí               0.0       0.000000    0.000000  15.540484   0.000000  

[110 rows x 110 columns]

In [23]:
matriz.to_csv("MatrizAdjacencia.csv")

In [30]:
def buscaLargura(grafoBusca: Grafo, origem: Vertice):

    # Montando tabela
  header = [v.getRotulo() for v in grafoBusca.vertices]
  indices = ['TD','TT', 'Pai']

  matriz = []
  # Lista de vertices não explorados
  nao_explorados = list(grafoBusca.vertices)
  
  # Matriz zerada
  for linhas in range(len(indices)):
    m = []
    for cols in range(len(header)):
        m.append(0)

    matriz.append(m)

  matrizDF = pd.DataFrame(matriz, index=indices ,columns=header)
  marcados = []
  explorados = []
  ultimo_analisado = None

  tempo = 0
  # Parada: todos os vértices explorados
  while(len(nao_explorados) > 0):
    if tempo == 0:
        em_analise = origem
    else:
        # em_analise =
        pass
     
    # Marca vértice em análise
    marcados.append(nao_explorados.pop(nao_explorados.index(em_analise)))
    matrizDF.at['TD' , em_analise.getRotulo()] = tempo
    tempo += 1
    matrizDF.loc[matrizDF['Pai'], em_analise.getRotulo() ] = ultimo_analisado

    # Explorar vertices:
    for ars in em_analise.arestasIncidentes:
        destino = filter(lambda a: a != origem, ars)
        if not (destino in marcados):
            marcados.append(nao_explorados.pop(nao_explorados.index(destino)))
            matrizDF.at['TD' , destino.getRotulo()] = tempo
            tempo +=1

    # Recebe vértice com menor TD


    # em_analise
    explorados.append(marcados.pop(marcados.index(em_analise)))
    matrizDF.at['TT' , explorados.getRotulo()] = tempo
    tempo+=1


In [31]:
# Executa a busca
buscaLargura(grafoCidades, grafoCidades.vertices[0])


     São Paulo  Rio de Janeiro  Belo Horizonte  Brasília  Salvador  Fortaleza  \
TD           0               0               0         0         0          0   
TT           0               0               0         0         0          0   
Pai          0               0               0         0         0          0   

     Curitiba  Manaus  Recife  Belém  ...  Parnamirim  Sumaré  Ipatinga  \
TD          0       0       0      0  ...           0       0         0   
TT          0       0       0      0  ...           0       0         0   
Pai         0       0       0      0  ...           0       0         0   

     Volta Redonda  Barueri  Imperatriz  Foz do Iguaçu  Cascavel  Viamão  \
TD               0        0           0              0         0       0   
TT               0        0           0              0         0       0   
Pai              0        0           0              0         0       0   

     Gravataí  
TD          0  
TT          0  
Pai         0  

[3 r

KeyError: 'Pai'